name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build server (Windows)
        working-directory: ./server
        run: cargo build --target x86_64-pc-windows-gnu --verbose

      - name: Build steamdeck (Windows)
        working-directory: ./steamdeck
        run: cargo build --target x86_64-pc-windows-gnu --verbose
