name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build server
        working-directory: ./server
        run: cargo build --verbose

      - name: Test server
        working-directory: ./server
        run: cargo test --verbose

      - name: Build steamdeck
        working-directory: ./steamdeck
        run: cargo build --verbose

      - name: Test steamdeck
        working-directory: ./steamdeck
        run: cargo test --verbose
