name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build project1 for Windows
        working-directory: ./project1
        run: cargo build --target x86_64-pc-windows-gnu --verbose

      - name: Build project2 for Windows
        working-directory: ./project2
        run: cargo build --target x86_64-pc-windows-gnu --verbose
