name: Rust Artifacts

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build server
        working-directory: ./server
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu

      - name: Build steamdeck
        working-directory: ./steamdeck
        run: cargo build --release

      - name: Upload server executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: server.exe
          path: ./server/target/x86_64-pc-windows-gnu/release/server.exe

      - name: Upload steamdeck executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: steamdeck.exe
          path: ./steamdeck/target/release/steamdeck.exe
